image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm install
    command: hugo serve --baseURL https://1313-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}/ --appendPort=false

ports:
  - port: 1313
    onOpen: ignore

vscode:
  extensions:
    - eliostruyf.vscode-front-matter
    - bungcip.better-toml
    - budparr.language-hugo-vscode
    - ms-azuretools.vscode-docker
